
server:
  port: 8082
spring:
  application:
    name: SERVICE-CAR
  datasource:
    url:  jdbc:mysql://localhost:3306/voitureDb?createDatabaseIfNotExist=true
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
