server:
  port: 8081
spring:
  application:
    name: SERVICE-CLIENT
  datasource:
    url:  jdbc:mysql://localhost:3306/clientDb?createDatabaseIfNotExist=true
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

